apiVersion: apps/v1
kind: Deployment
metadata:
  name: couber
  labels:
    app: couber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couber
  template:
    metadata:
      labels:
        app: couber
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: couber
        image: erebe/couber:latest
        imagePullPolicy: Always
        env:
        - name: PORT
          value: "8081"
        ports:
        - containerPort: 8081
        volumeMounts:
        - name: db
          mountPath: /home/app/db
        - name: videos
          mountPath: /home/app/videos
      volumes:
      - name: db
        hostPath:
          path: /home/erebe/db/
          type: Directory
      - name: videos
        hostPath:
          path: /home/erebe/Ressources/videos/
          type: Directory

---
apiVersion: v1
kind: Service
metadata:
  name: couber
spec:
  selector:
    app: couber
  ports:
    - protocol: TCP
      port: 8081
  clusterIP: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: couber-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: couber
          servicePort: 8081
